### ISSUE TITLE
Data labeling

### ISSUE THREAD

**Issue by SeongJaeSong** [kookmin-sw/capstone-2020-1#10]
영상 매칭 또는 유사도를 이용하여 데이터 라벨링

**Comment by SeongJaeSong** [comment]
datalabeling 브랜치 생성

**Comment by yeonsookim40282628** [comment]
브랜치 다시만들어야합니다

**Comment by SeongJaeSong** [comment]
datalabeling 브랜치 삭제

**Comment by SeongJaeSong** [comment]
프로젝트의 방향성을 변경하여 하이라이트 지점을 판별하는데 영상 데이터를 사용하지 않기 때문에 데이터를 라벨링 하지 않아도 되므로 이슈 닫습니다.
