### ISSUE TITLE
Sign Up 버튼 클릭시 개선사항

### ISSUE THREAD

**Issue by SeongJaeSong** [kookmin-sw/capstone-2020-1#117]
![image](https://user-images.githubusercontent.com/58547105/82799017-53799400-9eb4-11ea-89a9-e37398e9417d.png)

Sign Up 버튼 클릭 시 모달이 뜨는데 가장 위 입력창(Email)이 아닌 가장 아래 입력창(Age)이 활성화 되있음

**Comment by sshun21** [comment]
해결
