### ISSUE TITLE
로고 및 제목 수정 요청

### ISSUE THREAD

**Issue by SeongJaeSong** [kookmin-sw/capstone-2020-1#118]
![image](https://user-images.githubusercontent.com/58547105/82799216-a6ebe200-9eb4-11ea-8624-c45ca43a2bf5.png)

사이트의 로고와 제목이 기본값으로 설정되어있음

**Comment by sshun21** [comment]
<img width="332" alt="image" src="https://user-images.githubusercontent.com/13410449/82879679-3dcda280-9f78-11ea-9849-baa8db6bbe2d.png">
해결 완료
