### ISSUE TITLE
로그인 후 환영 인사 및 로그아웃

### ISSUE THREAD

**Issue by SeongJaeSong** [kookmin-sw/capstone-2020-1#119]
![image](https://user-images.githubusercontent.com/58547105/82799342-df8bbb80-9eb4-11ea-94c4-37ae6659b602.png)

위와 같이 이메일 + 환영인사로 되어있는데
이름 + 환영인사가 일반적이라고 생각됨.

또, 환영인사를 클릭하면 로그아웃이 되는데 로그아웃 버튼을 따로 빼는게 나을 것 같음.

**Comment by sshun21** [comment]
백앤드 수정후 구현 예정

**Comment by sshun21** [comment]
로그아웃 버튼 생성 완료 username은 추후 예정
