### ISSUE TITLE
CSS 수정 요청

### ISSUE THREAD

**Issue by SeongJaeSong** [kookmin-sw/capstone-2020-1#120]
![image](https://user-images.githubusercontent.com/58547105/82799569-342f3680-9eb5-11ea-8c7a-49cf6365e10a.png)

위 배너(?) 부분의 정렬이 맞지않고 의미없는 가로 스크롤이 생성되며 우측 끝쪽의 이미지가 깨짐

**Comment by sshun21** [comment]
해결
