### ISSUE TITLE
하이라이트 결과 표 가독성 문제

### ISSUE THREAD

**Issue by SeongJaeSong** [kookmin-sw/capstone-2020-1#121]
![image](https://user-images.githubusercontent.com/58547105/82799728-735d8780-9eb5-11ea-8201-7f460632feea.png)

여백이 지나치게 많아 가독성이 떨어지고 특정 하이라이트 지점을 선택했을 때 영상이 해당 지점으로 이동되는 기능이 있는데, 마우스 포인터의 변화가 없음(클릭 가능하면 손가락 모양)

**Comment by sshun21** [comment]
사이즈 줄이고 테이블 누르면 hover 효과를 줌
<img width="947" alt="image" src="https://user-images.githubusercontent.com/13410449/82882549-2d1f2b80-9f7c-11ea-8924-65c887e9c520.png">
