### ISSUE TITLE
Positive&Negative 차트 hover 개선 요구

### ISSUE THREAD

**Issue by SeongJaeSong** [kookmin-sw/capstone-2020-1#122]
![image](https://user-images.githubusercontent.com/58547105/82799880-b7e92300-9eb5-11ea-8e35-227234cf17a1.png)
![image](https://user-images.githubusercontent.com/58547105/82799928-ca635c80-9eb5-11ea-90b3-e6169f68daea.png)
![image](https://user-images.githubusercontent.com/58547105/82799938-cdf6e380-9eb5-11ea-972d-68d31a0c86f2.png)
![image](https://user-images.githubusercontent.com/58547105/82800024-f088fc80-9eb5-11ea-8701-c09c2afeaf8b.png)
![image](https://user-images.githubusercontent.com/58547105/82800055-fe3e8200-9eb5-11ea-8955-c356775c823f.png)

위 사진들과 같이 마우스를 올릴때 마다 Negative 좌측 네모의 색이 변함.
Positive도 마찬가지

**Comment by SeongJaeSong** [comment]
7감정 분류에서도 동일한 문제 발생

**Comment by sshun21** [comment]
현상 파악 완료
