### ISSUE TITLE
데이터 분석 시각화 부분 개선 요구

### ISSUE THREAD

**Issue by SeongJaeSong** [kookmin-sw/capstone-2020-1#124]
Other에 추가 될 기능이 없다면 삭제

**Comment by SeongJaeSong** [comment]
![image](https://user-images.githubusercontent.com/58547105/82800522-d00d7200-9eb6-11ea-814c-7137b0d6460f.png)

각 항목을 처음 눌렀을 때 상단의 Option이 파란 글씨로 표현되고 Option 텍스트를 클릭하면 색이 변하는 버그가 있음

![image](https://user-images.githubusercontent.com/58547105/82800526-d3a0f900-9eb6-11ea-9f0d-0511047bbe32.png)

**Comment by sshun21** [comment]
other는 삭제 완료. 해당 오류는 큰 이슈가 아닌듯함. 추후 진행 예정

**Comment by sshun21** [comment]
현상 파악 완료. 옵션 을 선택 했을 때만 options 가 선택 됐다고 파란색이 되고 다른 event가 일어나면 options 글씨가 원래대로 회색으로 돌아옴
