### ISSUE TITLE
아프리카 영상 하이라이트 탐색 기능 수정 요청

### ISSUE THREAD

**Issue by SeongJaeSong** [kookmin-sw/capstone-2020-1#126]
![image](https://user-images.githubusercontent.com/58547105/82800879-5fb32080-9eb7-11ea-922b-97d4d5b5fe0b.png)

아프리카 영상의 경우 Highlight 지점을 클릭해도 해당 지점으로 이동하지 않으므로 
Click on the "Highligh Point" table to go to the click position
문구를 없애거나 아프리카는 해당 기능을 제공하지 않는다라고 명시하면 좋을 것 같음

**Comment by sshun21** [comment]
해결 완료
