### ISSUE TITLE
웹페이지에 로그인시 프로젝트 사용법이 보이도록 추가

### ISSUE THREAD

**Issue by asurava** [kookmin-sw/capstone-2020-1#138]
frontend-compose 브랜치에서 frontend-compose-usage 브랜치로 분기하여 작업을 진행하였습니다.

**Comment by asurava** [comment]
22451715cd42021a885921e07a67446cbf1142c7 커밋하였습니다!

**Comment by asurava** [comment]
![dd](https://user-images.githubusercontent.com/22051174/83544711-49513880-a539-11ea-8c67-96419d6ecd8f.png)

**Comment by sshun21** [comment]
조합이 독특한데 ...
1단계 로그인 -> 2단계 url 입력  ->  3단계 분석결과 확인 ->  4단계 결과를 통해 편집 와 같은 순으로 Usage 작성해 주시고 배경사진은.. 빼시고 각 단계별로 해당하는 플래티콘 같은걸 넣어주세요 깔끔해보이겜

**Comment by sshun21** [comment]
<img width="453" alt="image" src="https://user-images.githubusercontent.com/13410449/83546293-68e96080-a53b-11ea-92b8-c3fa7eb84933.png">

**Comment by asurava** [comment]
![dd](https://user-images.githubusercontent.com/22051174/83597270-ddef8100-a5a1-11ea-9feb-58ff22fbbebb.png)
이렇게 수정하여 커밋했습니다! 또 이상한 거 있으면 말해주세요!

**Comment by sshun21** [comment]
<img width="152" alt="image" src="https://user-images.githubusercontent.com/13410449/83598957-02e5f300-a5a6-11ea-9d68-eabdf88c460f.png">

**Comment by sshun21** [comment]
요런 느낌이면 좋겠습니답!!

**Comment by sshun21** [comment]
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/13410449/83612447-616a9b80-a5bd-11ea-8692-18fff7c5bee2.png">
다음과 같이 변경!

**Comment by sshun21** [comment]
추가적으로 홈페이지 구성도 바꾸고 정리 완료
