### ISSUE TITLE
풀영상에서 heuristic하게 추출한 지점이 하이라이트에 있는지 검증

### ISSUE THREAD

**Issue by asurava** [kookmin-sw/capstone-2020-1#14]
채팅과 소리를 기반으로 풀영상에서 heuristic하게 추출한 지점이 하이라이트에도 있는지를 확인하여 본 프로젝트의 타당성을 검증한다.

**Comment by asurava** [comment]
[sound + 채팅 테스트.pdf](https://github.com/kookmin-sw/capstone-2020-1/files/4431878/sound.%2B.pdf)

**Comment by SeongJaeSong** [comment]
solved.
