### ISSUE TITLE
회원정보

### ISSUE THREAD

**Issue by yeonsookim40282628** [kookmin-sw/capstone-2020-1#19]
자체 회원가입 만들것인지?
회원정보에 어떤것들이 필요한지? 예) 아이디, 비번, 이름 등

**Comment by SeongJaeSong** [comment]
만든다고했었고, 아이디 비밀번호 이름만 쓰면 될듯?

**Comment by yeonsookim40282628** [comment]
아이디는 이메일형식으로?

**Comment by SeongJaeSong** [comment]
상훈이형이랑 얘기해봐야할거 같은데 구글 로그인 쓸거면 그냥 이메일 말고 string으로 해도될듯

**Comment by sshun21** [comment]
내일 회의할때 이야기 정리 해서 이슈에서 올립시답
