### ISSUE TITLE
긍정부정 분류 모델 토크나이저 변경

### ISSUE THREAD

**Issue by SeongJaeSong** [kookmin-sw/capstone-2020-1#39]
기존에는 Okt 토크나이저를 사용했으나 SPM를 사용해 결과를 비교해보라는 조언을 받음.

**Comment by sshun21** [comment]
워크 플로우를 공유 부탁.

**Comment by SeongJaeSong** [comment]
현재
리뷰데이터 수집(네이버 영화 리뷰 15만) => 데이터셋 토크나이징(Okt 토크나이저) => 데이터셋 임베딩(BOW 등) => 모델 학습(MLP: Input - dense - dense - (sigmoid)output)

변경 후
리뷰데이터 수집(네이버 영화 리뷰 15만) => 데이터셋 토크나이징(SPM 토크나이저) => 데이터셋 임베딩(BOW 등) => 모델 학습(MLP: Input - dense - dense - (sigmoid)output)

** 토크나이징 부분에서 어떤 토크나이저를 사용할지에 대한 변경만 있습니다.

**Comment by SeongJaeSong** [comment]
기존의 Okt 토크나이저에서 SPM 토크나이저로 변경했고, 각 토크나이저의 분류 성능을 평가하기 위한 채팅 데이터셋 구축 중.

**Comment by SeongJaeSong** [comment]
Okt 토크나이저에 비해 SPM 토크나이저가 메모리를 많이 사용하여 기존의 Okt 토크나이저를 사용할 때는 최빈 토큰 10000개를 사용했으나 SPM 토크나이저를 사용할 때는 최빈 토큰 5000개 까지만 사용할 수 있음.

**Comment by SeongJaeSong** [comment]
Okt 토크나이저를 사용해 실제 채팅 데이터를 이용해 모델을 평가한 결과 정확도 71.38%가 나왔고,
SPM 토크나이저를 이용한 평가 결과 정확도 86.03%가 나왔다.

SPM 토크나이저를 이용해 유의미한 성능 개선이 있었다.
