### ISSUE TITLE
url 타당성 검증 api 연결

### ISSUE THREAD

**Issue by sshun21** [kookmin-sw/capstone-2020-1#74]

**Comment by sshun21** [comment]
url 요청시에 트위치, 유튜브, 아프리카 주소가 아닌 다른 텍스트를 입력하면 서버에서 오류를 발생함

**Comment by JeongyeonYun** [comment]
try/except를 통해 정상적으로 플랫폼에 접속할 수 있는 경우를 제외하고는 False를 리턴하도록 수정
