### ISSUE TITLE
Youtube 채팅로그 다운로드 예외

### ISSUE THREAD

**Issue by SeongJaeSong** [kookmin-sw/capstone-2020-1#82]
![image](https://user-images.githubusercontent.com/58547105/81666524-bdd21380-9474-11ea-9a76-bc01e6da2079.png)

위 사진과 같이 유튜브에서 제공하는 이모티콘을 사용한 채팅의 경우 채팅 로그에 채팅 내용이 나타나지 않음.

**Comment by JeongyeonYun** [comment]
이모티콘을 사용한 채팅의 경우 사용자의 채팅 내역을 삭제하고 진행하였습니다.
