### ISSUE TITLE
sound normalize 코드 정리 요청

### ISSUE THREAD

**Issue by yeonsookim40282628** [kookmin-sw/capstone-2020-1#95]
무리한 함수화로 인해 가독성, 직관성이 부족해진것같음. 409는 test에서도 오류나서 지우긴했는데 왜 필요한지 알수없음.

**Comment by yeonsookim40282628** [comment]
사용되지 않는 변수 등 불필요 코드 제거 부탁~

**Comment by asurava** [comment]
ad01eefe2f39554374a8ebdcc88c52f564714250 불필요한 변수와 함수 등을 제거했습니다!
